---
title: "Barrier Analysis"
author: "Giulio Fantuzzi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(patchwork)
```


# Barrier analysis

First of all, import the datasets i obtained from *ORFEO*
```{r}
barrier_default.df<- read.csv(file = "barrier_default.csv")
barrier_linear.df<- read.csv(file = "barrier_linear.csv")
barrier_doublering.df<- read.csv(file = "barrier_doublering.csv")
barrier_recursivedoubling.df<- read.csv(file = "barrier_recursivedoubling.csv")
barrier_bruck.df<- read.csv(file = "barrier_bruck.csv")
barrier_tree.df<- read.csv(file = "barrier_tree.csv")
```

Now we can bind them into a single df:
```{r}
barrier.df<- rbind(barrier_default.df,barrier_linear.df,barrier_doublering.df,barrier_recursivedoubling.df,barrier_bruck.df,barrier_tree.df)
```



```{r,fig.width=8, fig.height=5}
barrier.df %>% filter(Allocation == "core") %>% filter(Algorithm %in% c("Tree","Linear","Bruck") )%>% 
  ggplot(aes(x = Processes, y = Latency, color = Algorithm)) +
    geom_line(linetype = 1) +
    geom_point(size=1)+
    #geom_abline(slope = 0.19, intercept = -0.19, color = "red")+
    geom_vline(xintercept = c(12, 24), linetype = "dashed", color = "#616A6B")+
    annotate("text", x = c(12,24), y = c(0,0), label = c("12 Cores","24 cores"), vjust = 0, hjust = -0.1,color="#616A6B")+
    #scale_color_manual(values = c("#27AE60","#E67E22","#3498DB","#8E44AD","")) +
    xlim(2, 48) +
    labs(x = 'N. of processes (#cores)',
         y = 'Latency',
         title = 'Barrier Latency vs #cores (by Algorithm)',
         color = 'Algorithm')+
    theme_light()
```

ì